"""added is_pro and expiration_Date

Revision ID: 0cd9ccec5588
Revises: 5de1af939314
Create Date: 2026-01-02 01:45:26.449100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd9ccec5588'
down_revision: Union[str, Sequence[str], None] = '5de1af939314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_pro', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trial_ends_at')
    op.drop_column('users', 'is_pro')
    # ### end Alembic commands ###
