"""change the default value for created by

Revision ID: 1da2d31f71e8
Revises: 9886d8a47732
Create Date: 2026-01-29 11:12:56.412132

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da2d31f71e8'
down_revision: Union[str, Sequence[str], None] = '9886d8a47732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True))
    current_time = datetime.now(timezone.utc)
    op.execute(f"UPDATE subscriptions SET created_at = '{current_time}' WHERE created_at IS NULL")
    
    # 3. Now that there are no NULLs, set nullable to False
    op.alter_column('subscriptions', 'created_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'created_at')
    # ### end Alembic commands ###
