"""added quiz_type 2

Revision ID: 201646c00138
Revises: 67a1153f1a6f
Create Date: 2025-12-30 00:10:17.099995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '201646c00138'
down_revision: Union[str, Sequence[str], None] = '67a1153f1a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('quiz_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'quiz_type')
    # ### end Alembic commands ###
