"""added_cascades_and_subscription_fix

Revision ID: 433ea1c19e99
Revises: 932ac4ff105c
Create Date: 2025-12-30 16:12:55.360735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433ea1c19e99'
down_revision: Union[str, Sequence[str], None] = '932ac4ff105c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
