"""make is_admin nullable

Revision ID: 4474e1a650d4
Revises: 8e9e1922344b
Create Date: 2025-12-24 15:08:11.771032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4474e1a650d4'
down_revision: Union[str, Sequence[str], None] = '8e9e1922344b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_sources', 'storage_path')
    op.alter_column('users', 'is_admin', existing_type=sa.Boolean(), nullable=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_sources', sa.Column('storage_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
