"""added is_admin

Revision ID: 709a9ee4e807
Revises: 7bcaba46e202
Create Date: 2025-12-29 19:53:06.206155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709a9ee4e807'
down_revision: Union[str, Sequence[str], None] = '7bcaba46e202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'quiz_type')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.add_column('quizzes', sa.Column('quiz_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
