"""added extra fields to quiz

Revision ID: 7bcaba46e202
Revises: 4474e1a650d4
Create Date: 2025-12-25 19:52:59.266254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bcaba46e202'
down_revision: Union[str, Sequence[str], None] = '4474e1a650d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('quizzes', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('quizzes', sa.Column('time_limit', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_quizzes_user_id'), 'quizzes', ['user_id'], unique=False)
    op.create_foreign_key(None, 'quizzes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_index(op.f('ix_quizzes_user_id'), table_name='quizzes')
    op.drop_column('quizzes', 'time_limit')
    op.drop_column('quizzes', 'title')
    op.drop_column('quizzes', 'user_id')
    # ### end Alembic commands ###
