"""revert added_cascades_and_subscription_fix

Revision ID: 8327f835a06b
Revises: 433ea1c19e99
Create Date: 2025-12-30 16:19:17.198171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8327f835a06b'
down_revision: Union[str, Sequence[str], None] = '433ea1c19e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
