"""revert some cascade delete orphans

Revision ID: 932ac4ff105c
Revises: 95e4cbe352e1
Create Date: 2025-12-30 16:00:55.894548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '932ac4ff105c'
down_revision: Union[str, Sequence[str], None] = '95e4cbe352e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
