"""cascade delete orphans

Revision ID: 95e4cbe352e1
Revises: 0ac5b7d1cc71
Create Date: 2025-12-30 15:42:42.512538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e4cbe352e1'
down_revision: Union[str, Sequence[str], None] = '0ac5b7d1cc71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
