"""added new start_page and end_page to quizSoruce

Revision ID: a1f12c580c4d
Revises: c65666678741
Create Date: 2026-01-01 19:52:01.187240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f12c580c4d'
down_revision: Union[str, Sequence[str], None] = 'c65666678741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_sources', sa.Column('start_page', sa.Integer(), nullable=True))
    op.add_column('quiz_sources', sa.Column('end_page', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_sources', 'end_page')
    op.drop_column('quiz_sources', 'start_page')
    # ### end Alembic commands ###
