"""make quiz type nullable

Revision ID: dc1422e74031
Revises: 201646c00138
Create Date: 2025-12-30 00:32:29.875399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc1422e74031'
down_revision: Union[str, Sequence[str], None] = '201646c00138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes', 'quiz_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes', 'quiz_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
